# Generated by Django 5.2.6 on 2025-10-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students_photos/'),
        ),
    ]
